spring:
  profiles:
    active:
      - local
server:
  port: 8080
  servlet:
    context-path: /lunar/admin

###################################################################################################
##  LOCAL
###################################################################################################
---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/lunar_db?serverTimezone=UTC&characterEncoding=UTF-8&passwordCharacterEncoding=UTF-8
    username: root
    password: lois@1234
  jwt:
    secret: lunarTokenSecretKeyakfldhxkdnjpowersecret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      #create: 테이블 삭제, 생성 / create-drop: 종료 시점에 테이블 삭제 / update: 변경부분만 반영 / validate: 정상 매핑 검증 / none: 초기화 안함.
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  ## logging
  logging:
    file:
      path: C:\svc\wiseai-admin-logs
    level:
      root: info
      kr.co.wiseai.admin: debug
      org.springframework.web: trace
      sql: error
      jdbc: off
      jdbc.sqlonly: info
      jdbc.connection: off
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
