spring:
  profiles:
    active:
      - local
server:
  port: 8080
  servlet:
    context-path: /lunar/admin

###################################################################################################
##  LOCAL
###################################################################################################
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.27.168.25:3306/lunar_db?serverTimezone=UTC&characterEncoding=UTF-8&passwordCharacterEncoding=UTF-8
    username: root
    password: lois@1234
    hikari:
      maximum-pool-size: 100
      minimumIdle: 25
      idleTimeout: 10000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 420000
      connection-timeout: 10000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      #create: 테이블 삭제, 생성 / create-drop: 종료 시점에 테이블 삭제 / update: 변경부분만 반영 / validate: 정상 매핑 검증 / none: 초기화 안함
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jwt:
    secret: lunarTokenSecretKeyakfldhxkdnjpowersecret

  ## logging
  logging:
    file:
      path: C:\svc\lunar-admin-logs
    level:
      root: info
      com.lunar.lunarMgmt.admin: debug
      org.springframework.web: trace
      sql: error
      jdbc: off
      jdbc.sqlonly: info
      jdbc.connection: off
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

menu-file:
  upload-path: C:\lunar\menu\

system:
  swagger:
    host: localhost:8080 #swagger-ui.html -> nuxt front server에 요청하도록 (because of token) 추후 3000으로 변경될 예정
    protocols: http, https
---
